-- Eliminar tablas

DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Tutor;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Student_Course;
DROP TABLE IF EXISTS Task;
DROP TABLE IF EXISTS Criteria;
DROP TABLE IF EXISTS Submission;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Review_Criteria;